[workspace]
resolver = "2"
members = [
    "apps/server",
    "apps/host/src-tauri",
    "engine", "shared"
]

# Share core dependencies across the workspace to speed up compile times
[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
