#!/usr/bin/env bash
# Export just the chart text from songs/ into a directory ready to commit to the
# private chart-data repo that seed-charts.yml reads.
#
#   scripts/export-chart-text.sh                     # dry run (default)
#   scripts/export-chart-text.sh --apply ../maiscope-chart-data
#
# WHY ONLY maidata.txt: bin/seed_songs opens nothing else. It never reads
# track.mp3, pv.mp4 or bg.jpg, which is the entire ~16GB. The chart text is
# 1928 files / ~17.5MB raw / ~3.9MB gzipped, so the data repo is an ordinary git
# repo — no LFS, no object storage. Copying the audio and video in would make it
# unclonable in CI for no benefit.
#
# The output keeps the flat songs/<song>/maidata.txt shape seed_songs expects: it
# reads one level deep and does not recurse, so a <version>/<song>/ layout
# silently matches nothing. Run scripts/flatten-songs.sh first if needed.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
WORKSPACE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
SONGS_DIR="${SONGS_DIR:-$WORKSPACE_DIR/songs}"

APPLY=0
DEST=""
for arg in "$@"; do
  case "$arg" in
    --apply) APPLY=1 ;;
    -h | --help)
      sed -n '2,18p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    -*)
      echo "export-chart-text: unknown flag '$arg' (try --help)" >&2
      exit 2
      ;;
    *) DEST="$arg" ;;
  esac
done

[ -d "$SONGS_DIR" ] || {
  echo "export-chart-text: no such directory: $SONGS_DIR" >&2
  exit 1
}

# Same song-directory test seed_songs uses: contains a maidata.txt, one level down.
mapfile -t -d '' SONG_DIRS < <(
  find "$SONGS_DIR" -mindepth 1 -maxdepth 1 -type d -exec test -e '{}/maidata.txt' \; -print0 | sort -z
)
nested=$(find "$SONGS_DIR" -mindepth 1 -maxdepth 1 -type d ! -exec test -e '{}/maidata.txt' \; -print | wc -l)

if [ ${#SONG_DIRS[@]} -eq 0 ]; then
  echo "export-chart-text: no song directory under $SONGS_DIR contains a maidata.txt." >&2
  echo "                   If the tree is <version>/<song>/, flatten it first:" >&2
  echo "                   scripts/flatten-songs.sh --apply" >&2
  exit 1
fi

bytes=$(printf '%s\0' "${SONG_DIRS[@]}" | xargs -0 -I{} stat -c '%s' '{}/maidata.txt' | awk '{s+=$1} END {print s+0}')
printf 'export-chart-text: %d song directories, %.1f MB of chart text\n' \
  "${#SONG_DIRS[@]}" "$(awk -v b="$bytes" 'BEGIN {print b/1048576}')"
[ "$nested" -gt 0 ] && echo "                   note: $nested top-level directories have no maidata.txt and are ignored"

if [ "$APPLY" -eq 0 ]; then
  echo
  echo "  DRY RUN — nothing written. First 5 of ${#SONG_DIRS[@]}:"
  for i in "${!SONG_DIRS[@]}"; do
    [ "$i" -ge 5 ] && break
    echo "    songs/$(basename "${SONG_DIRS[$i]}")/maidata.txt"
  done
  echo
  echo "  re-run as: scripts/export-chart-text.sh --apply <dest-dir>"
  exit 0
fi

[ -n "$DEST" ] || {
  echo "export-chart-text: --apply needs a destination directory" >&2
  exit 2
}

mkdir -p "$DEST/songs"
copied=0
for sdir in "${SONG_DIRS[@]}"; do
  song="$(basename "$sdir")"
  mkdir -p "$DEST/songs/$song"
  cp -p "$sdir/maidata.txt" "$DEST/songs/$song/maidata.txt"
  copied=$((copied + 1))
done

# Carry the version manifest across when flatten-songs.sh wrote one. It is the
# only record of which maimai version each song came from — maidata.txt has no
# version field — so the data repo should hold it too.
if [ -e "$SONGS_DIR/.songs-layout.tsv" ]; then
  cp -p "$SONGS_DIR/.songs-layout.tsv" "$DEST/songs/.songs-layout.tsv"
  echo "export-chart-text: copied .songs-layout.tsv (the only record of version grouping)"
fi

cat >"$DEST/README.md" <<'EOF'
# maiscope chart data

Chart text for [maiscope](https://github.com/tuthanhh/maiscope), kept out of the
public repo. Generated by that repo's `scripts/export-chart-text.sh`.

## Layout

```
songs/<song>/maidata.txt
songs/.songs-layout.tsv     # which maimai version each song came from
```

Flat on purpose: `bin/seed_songs` reads `<songs-dir>/<song>/maidata.txt` exactly
one level deep and does not recurse, so a `<version>/<song>/` layout silently
matches nothing and skips every song.

`maidata.txt` only. Audio, video and jacket art are deliberately absent —
`seed_songs` never opens them, and they are ~16GB against this repo's ~17.5MB.

`.songs-layout.tsv` is the sole record of the version each song belongs to;
`maidata.txt` carries `&title`, `&artist`, `&wholebpm` and `&lv_*` but no version
field. Do not delete it.

## Consumed by

- `seed-charts.yml` — reads this repo, seeds chart text into production
- `backup-database.yml` — writes `pg_dump` output to `backups/`
EOF

printf 'export-chart-text: wrote %d maidata.txt files to %s\n' "$copied" "$DEST"
echo "                   next: cd $DEST && git init && git add -A && git commit"
